-- Multitenancy foundations — schema + data migration only (see docs/multitenancy-plan.md).
--
-- This migration is hand-written rather than generated by `scripts/migrate.mjs create`:
-- this database has PL/pgSQL trigger functions in "public" (from append_only_guards), and
-- the bundled @prisma/schema-engine-wasm's Postgres introspection connector cannot
-- deserialize the `"char"` typed columns it encounters while cataloguing routines
-- (pg_proc.prokind/provolatile/proparallel), so `engine.introspect()` throws and the
-- `create` command silently falls back to diffing from an empty schema — which would
-- emit a full CREATE TABLE recreate of the whole database instead of an incremental
-- diff. Hand-authoring avoids that (matches the pattern already used by the other
-- non-init migrations in this project for the same reason).
--
-- Scope (explicitly agreed with the user): schema + one-time data backfill only. No
-- auth/session/service-layer code changes here. The 32 pre-existing tables below each
-- get a *soft* `zevId` column — nullable, no foreign key, no inverse relation on Zev —
-- a deliberate transitional halfway state. Enforcing NOT NULL + real relations, and
-- tenant-scoping existing unique constraints, is deferred to the auth-layer cutover
-- step (see the banner comment on the Zev model in schema.prisma).

-- CreateEnum
CREATE TYPE "ZevTier" AS ENUM ('BASIC', 'BASIC_FINANCE', 'FULL');

-- AlterTable: Zev gains tier + active
ALTER TABLE "Zev" ADD COLUMN "tier" "ZevTier" NOT NULL DEFAULT 'FULL';
ALTER TABLE "Zev" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable: platform-level super admin flag on User
ALTER TABLE "User" ADD COLUMN "isSuperAdmin" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable: Membership (user <-> Zev <-> role), a real fully-declared relation
CREATE TABLE "Membership" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "zevId" TEXT NOT NULL,
    "role" "Role" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Membership_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Membership_userId_zevId_role_key" ON "Membership"("userId", "zevId", "role");

-- CreateIndex
CREATE INDEX "Membership_zevId_idx" ON "Membership"("zevId");

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_zevId_fkey" FOREIGN KEY ("zevId") REFERENCES "Zev"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AlterTable: soft tenant column (nullable, no FK — see banner comment above) on every
-- pre-existing model queried directly by the service layer.
ALTER TABLE "Party" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Entrance" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Unit" ADD COLUMN "zevId" TEXT;
ALTER TABLE "OwnershipStake" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Occupancy" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Proxy" ADD COLUMN "zevId" TEXT;
ALTER TABLE "OfficeTerm" ADD COLUMN "zevId" TEXT;
ALTER TABLE "AllocationGroup" ADD COLUMN "zevId" TEXT;
ALTER TABLE "CommonAsset" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Meeting" ADD COLUMN "zevId" TEXT;
ALTER TABLE "VotingRule" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Proposal" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Vote" ADD COLUMN "zevId" TEXT;
ALTER TABLE "TransactionCategory" ADD COLUMN "zevId" TEXT;
ALTER TABLE "FinTransaction" ADD COLUMN "zevId" TEXT;
ALTER TABLE "ChargeItem" ADD COLUMN "zevId" TEXT;
ALTER TABLE "InvoiceBatch" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Invoice" ADD COLUMN "zevId" TEXT;
ALTER TABLE "BankImportBatch" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Payment" ADD COLUMN "zevId" TEXT;
ALTER TABLE "BalanceCorrection" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Supplier" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Expense" ADD COLUMN "zevId" TEXT;
ALTER TABLE "AnnualPlan" ADD COLUMN "zevId" TEXT;
ALTER TABLE "PlanItem" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Project" ADD COLUMN "zevId" TEXT;
ALTER TABLE "MaintenanceIssue" ADD COLUMN "zevId" TEXT;
ALTER TABLE "WorkOrder" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Document" ADD COLUMN "zevId" TEXT;
ALTER TABLE "Attachment" ADD COLUMN "zevId" TEXT;
ALTER TABLE "NotificationMessage" ADD COLUMN "zevId" TEXT;
ALTER TABLE "AuditEvent" ADD COLUMN "zevId" TEXT;

-- Data migration: the existing (pre-multitenancy) demo/mock data becomes tenant #1.
-- Both backfills key off the single earliest-created Zev row. On a genuinely fresh/
-- empty database (db:reset before db:seed) there is no Zev yet, so the subquery
-- returns NULL and every statement below is a safe no-op (no rows exist to update,
-- and unnest() over an empty/no-role User set yields nothing to insert).
--
-- Vote and AuditEvent are append-only (see append_only_guards): a trigger rejects any
-- UPDATE, including this one-time system backfill. Disable just those two triggers for
-- the duration of this migration's backfill, then restore them immediately after —
-- application code never gets a window where the guard is off.

-- One Membership row per (User, role) currently in User.roles, all on tenant #1.
INSERT INTO "Membership" ("id", "userId", "zevId", "role", "createdAt")
SELECT gen_random_uuid()::text, u.id, z.id, r, now()
FROM "User" u
CROSS JOIN LATERAL unnest(u.roles) AS r
CROSS JOIN (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1) z
ON CONFLICT ("userId", "zevId", "role") DO NOTHING;

-- Backfill the new soft zevId column on every pre-existing row of the 32 tables above.
UPDATE "Party" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Entrance" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Unit" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "OwnershipStake" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Occupancy" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Proxy" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "OfficeTerm" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "AllocationGroup" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "CommonAsset" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Meeting" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "VotingRule" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Proposal" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
ALTER TABLE "Vote" DISABLE TRIGGER "vote_append_only";
UPDATE "Vote" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
ALTER TABLE "Vote" ENABLE TRIGGER "vote_append_only";
UPDATE "TransactionCategory" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "FinTransaction" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "ChargeItem" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "InvoiceBatch" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Invoice" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "BankImportBatch" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Payment" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "BalanceCorrection" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Supplier" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Expense" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "AnnualPlan" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "PlanItem" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Project" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "MaintenanceIssue" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "WorkOrder" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Document" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "Attachment" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
UPDATE "NotificationMessage" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
ALTER TABLE "AuditEvent" DISABLE TRIGGER "audit_event_append_only";
UPDATE "AuditEvent" SET "zevId" = (SELECT id FROM "Zev" ORDER BY "createdAt" ASC LIMIT 1);
ALTER TABLE "AuditEvent" ENABLE TRIGGER "audit_event_append_only";
